'use strict';

/**
 * Запускается в GitHub Actions.
 * Логинится в Google через Playwright, забирает cookies,
 * записывает в $GITHUB_ENV как YT_COOKIES.
 */

const { chromium } = require('playwright');
const fs           = require('fs');
const os           = require('os');

const sleep = ms => new Promise(r => setTimeout(r, ms));

function toNetscapeFormat(cookies) {
  const lines = ['# Netscape HTTP Cookie File', '# Auto-generated by GitHub Actions', ''];
  for (const c of cookies) {
    const domain  = c.domain.startsWith('.') ? c.domain : '.' + c.domain;
    const secure  = c.secure ? 'TRUE' : 'FALSE';
    const expires = c.expires > 0 ? Math.floor(c.expires) : Math.floor(Date.now() / 1000) + 86400 * 30;
    lines.push([domain, 'TRUE', c.path || '/', secure, expires, c.name, c.value].join('\t'));
  }
  return lines.join('\n');
}

async function main() {
  const email    = process.env.GOOGLE_EMAIL;
  const password = process.env.GOOGLE_PASSWORD;

  if (!email || !password) {
    console.error('❌ GOOGLE_EMAIL / GOOGLE_PASSWORD не заданы');
    process.exit(1);
  }

  console.log('🚀 Запускаем Playwright...');

  const browser = await chromium.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  const context = await browser.newContext({
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
    locale: 'en-US',
    viewport: { width: 1280, height: 800 },
  });

  const page = await context.newPage();

  try {
    // ── Шаг 1: Email ────────────────────────────
    console.log('📧 Вводим email...');
    await page.goto('https://accounts.google.com/signin/v2/identifier?hl=en', {
      waitUntil: 'networkidle',
      timeout: 30_000,
    });

    await page.waitForSelector('input[type="email"]', { timeout: 15_000 });
    await sleep(600);
    await page.fill('input[type="email"]', email);
    await sleep(400);
    await page.keyboard.press('Enter');

    // ── Шаг 2: Пароль ───────────────────────────
    console.log('🔑 Ждём поле пароля...');
    await page.waitForSelector('input[type="password"]', {
      state: 'visible',
      timeout: 20_000,
    });
    await sleep(600);
    await page.fill('input[type="password"]', password);
    await sleep(400);
    await page.keyboard.press('Enter');

    // ── Шаг 3: Ждём завершения входа ────────────
    console.log('⏳ Ждём завершения входа...');
    await page.waitForURL(url => !url.includes('accounts.google.com/signin'), {
      timeout: 20_000,
    });

    const finalUrl = page.url();
    console.log(`✅ Вход выполнен, URL: ${finalUrl}`);

    // ── Шаг 4: YouTube ──────────────────────────
    console.log('▶️  Переходим на YouTube...');
    await page.goto('https://www.youtube.com', {
      waitUntil: 'networkidle',
      timeout: 30_000,
    });
    await sleep(2_000);

    // ── Шаг 5: Собираем cookies ─────────────────
    const cookies = await context.cookies([
      'https://www.youtube.com',
      'https://accounts.google.com',
    ]);
    console.log(`🍪 Получено ${cookies.length} cookies`);

    if (cookies.length < 5) {
      throw new Error(`Слишком мало cookies: ${cookies.length}`);
    }

    const netscape = toNetscapeFormat(cookies);

    // ── Шаг 6: Пишем в GITHUB_ENV ───────────────
    // Многострочное значение через delimiter
    const delimiter = `EOF_${Date.now()}`;
    const envFile   = process.env.GITHUB_ENV;

    if (!envFile) {
      // Локальный запуск — просто выводим
      console.log('\n--- COOKIES ---\n', netscape.slice(0, 200), '\n...');
    } else {
      fs.appendFileSync(envFile, `YT_COOKIES<<${delimiter}\n${netscape}\n${delimiter}\n`);
      console.log('✅ YT_COOKIES записан в GITHUB_ENV');
    }

  } catch (err) {
    // Скриншот для диагностики
    const shot = `/tmp/debug_${Date.now()}.png`;
    await page.screenshot({ path: shot, fullPage: true }).catch(() => {});
    console.error(`❌ Ошибка: ${err.message}`);
    console.error(`   Скриншот: ${shot} (артефакт экшена)`);

    await browser.close();
    process.exit(1);
  }

  await browser.close();
  console.log('🎉 Готово!');
}

main();
