'use strict';

/**
 * 🍪 Auto Cookie Refresh
 * Логинится в Google через Puppeteer и обновляет cookies для yt-dlp
 */

const fs         = require('fs');
const os         = require('os');
const path       = require('path');
const puppeteer  = require('puppeteer-core');
const chromium   = require('@sparticuz/chromium');

const COOKIES_FILE   = path.join(os.tmpdir(), 'yt_cookies.txt');
const REFRESH_EVERY  = 3 * 24 * 60 * 60 * 1000; // 3 дня в мс

let refreshTimer     = null;
let isRefreshing     = false;
let lastRefreshAt    = null;
let lastRefreshOk    = false;

// ─────────────────────────────────────────────
// Конвертация Puppeteer cookies → Netscape формат для yt-dlp
// ─────────────────────────────────────────────

function toNetscapeFormat(cookies) {
  const lines = ['# Netscape HTTP Cookie File', '# Auto-generated by cookies-refresh.js', ''];
  for (const c of cookies) {
    const domain    = c.domain.startsWith('.') ? c.domain : '.' + c.domain;
    const httpOnly  = c.httpOnly ? 'TRUE' : 'FALSE';
    const secure    = c.secure   ? 'TRUE' : 'FALSE';
    const expires   = c.expires > 0 ? Math.floor(c.expires) : Math.floor(Date.now() / 1000) + 86400 * 30;
    lines.push([domain, 'TRUE', c.path, secure, expires, c.name, c.value].join('\t'));
  }
  return lines.join('\n');
}

// ─────────────────────────────────────────────
// Основная функция обновления cookies
// ─────────────────────────────────────────────

async function refreshCookies() {
  if (isRefreshing) {
    console.log('[cookies] Обновление уже идёт, пропускаем');
    return false;
  }

  const email    = process.env.GOOGLE_EMAIL;
  const password = process.env.GOOGLE_PASSWORD;

  if (!email || !password) {
    console.warn('[cookies] GOOGLE_EMAIL или GOOGLE_PASSWORD не заданы — пропускаем обновление');
    return false;
  }

  isRefreshing = true;
  console.log('[cookies] Начинаем обновление...');

  let browser = null;

  try {
    browser = await puppeteer.launch({
      args: [
        ...chromium.args,
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
        '--single-process',
      ],
      defaultViewport: chromium.defaultViewport,
      executablePath:  await chromium.executablePath(),
      headless:        chromium.headless,
    });

    const page = await browser.newPage();

    // Маскируем автоматизацию
    await page.setUserAgent(
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
    );
    await page.setExtraHTTPHeaders({ 'Accept-Language': 'ru-RU,ru;q=0.9' });

    // ── Шаг 1: открываем форму входа ───────────
    console.log('[cookies] Открываем Google Login...');
    await page.goto('https://accounts.google.com/signin/v2/identifier?hl=ru', {
      waitUntil: 'networkidle2',
      timeout:   30_000,
    });

    // ── Шаг 2: вводим email ────────────────────
    await page.waitForSelector('input[type="email"]', { timeout: 10_000 });
    await page.type('input[type="email"]', email, { delay: 80 });
    await page.keyboard.press('Enter');
    await page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 15_000 });

    // ── Шаг 3: вводим пароль ──────────────────
    await page.waitForSelector('input[type="password"]', { visible: true, timeout: 10_000 });
    await page.type('input[type="password"]', password, { delay: 80 });
    await page.keyboard.press('Enter');
    await page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 20_000 });

    // Проверяем: не застряли ли на 2FA или капче
    const currentUrl = page.url();
    if (currentUrl.includes('challenge') || currentUrl.includes('signin')) {
      throw new Error(`Требуется дополнительная проверка: ${currentUrl}`);
    }

    // ── Шаг 4: переходим на YouTube ───────────
    console.log('[cookies] Переходим на YouTube...');
    await page.goto('https://www.youtube.com', {
      waitUntil: 'networkidle2',
      timeout:   30_000,
    });

    // ── Шаг 5: собираем cookies ───────────────
    const cookies = await page.cookies('https://www.youtube.com', 'https://accounts.google.com');

    if (cookies.length < 5) {
      throw new Error(`Слишком мало cookies (${cookies.length}) — вход не выполнен`);
    }

    // ── Шаг 6: сохраняем в файл ───────────────
    const netscape = toNetscapeFormat(cookies);
    fs.writeFileSync(COOKIES_FILE, netscape, 'utf8');

    lastRefreshAt = new Date();
    lastRefreshOk = true;
    console.log(`[cookies] ✅ Обновлено ${cookies.length} cookies → ${COOKIES_FILE}`);

    return true;

  } catch (err) {
    lastRefreshOk = false;
    console.error('[cookies] ❌ Ошибка обновления:', err.message);

    // Если есть старые cookies — продолжаем работать с ними
    if (fs.existsSync(COOKIES_FILE)) {
      console.warn('[cookies] Используем предыдущие cookies');
    }

    return false;

  } finally {
    if (browser) await browser.close().catch(() => {});
    isRefreshing = false;
  }
}

// ─────────────────────────────────────────────
// Запуск и планировщик
// ─────────────────────────────────────────────

async function startCookieRefresh() {
  // При старте: сначала пробуем из ENV (быстрый путь),
  // потом через Puppeteer если ENV не задан
  if (process.env.YT_COOKIES) {
    fs.writeFileSync(COOKIES_FILE, process.env.YT_COOKIES, 'utf8');
    lastRefreshOk = true;
    lastRefreshAt = new Date();
    console.log('[cookies] Начальные cookies загружены из YT_COOKIES env');
  } else {
    // Первый запуск — сразу обновляем
    await refreshCookies();
  }

  // Планируем обновление каждые 3 дня
  refreshTimer = setInterval(async () => {
    console.log('[cookies] Плановое обновление...');
    await refreshCookies();
  }, REFRESH_EVERY);

  // Не блокируем завершение процесса
  refreshTimer.unref();
}

function stopCookieRefresh() {
  if (refreshTimer) clearInterval(refreshTimer);
}

function getCookiesFile() {
  return fs.existsSync(COOKIES_FILE) ? COOKIES_FILE : null;
}

function getRefreshStatus() {
  return {
    lastRefreshAt: lastRefreshAt?.toISOString() ?? null,
    lastRefreshOk,
    isRefreshing,
    cookiesExist: fs.existsSync(COOKIES_FILE),
    nextRefreshIn: refreshTimer
      ? `~${Math.round(REFRESH_EVERY / 3_600_000)}h`
      : 'не запланировано',
  };
}

module.exports = { startCookieRefresh, stopCookieRefresh, getCookiesFile, getRefreshStatus, refreshCookies };
